apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qkr2tdoyx-go
  janus-idp.io/tekton: qkr2tdoyx-go
  backstage.io/kubernetes-id: qkr2tdoyx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qkr2tdoyx-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
